const students = {
  "1st": [
    "Cristian Amezcua",
    "Michelle Angel Mendez",
    "Giorgia Cobas Pons",
    "Micah Corgill",
    "Alfredo Gonzalez",
    "Ky Anh Lam",
    "Gavin Latas",
    "Javier Leyva Bello",
    "Adrian McCasland",
    "Andrea Mejia Posadas",
    "Tony Mora Gonzalez",
    "Zaid Ordaz-Alvarado",
    "Lotfullah Pardis",
    "Kevin Santana",
    "Brooklyn Scott Mitchell",
    "Hamidullah Siraji",
    "Wudassie Tafesse",
    "Jezzelle Trevino",
    "Sebastian Vasquez Rico",
    "Cristina Villarreal",
    "Mohamad Zaloukh",
    "Oliver Brown",
    "Juleous Don",
    "Javion Gallegos",
    "Mark Maldonado",
    "Caprice Martinez",
    "Isabel Ramos",
    "Adrian Tovar-Rodriguez",
    "Jaeden Woods",
  ],
  "2nd": [
    "Alina Afalla",
    "Keren Banegas Murillo",
    "Santiago Barajas",
    "Jeremiah Beyene",
    "Estefany Botello-Ayala",
    "Zorah Brooks Richardson",
    "Maria Chavez Martinez",
    "Mariah Cheairs",
    "A'mya Collins",
    "Zullal Fayazi",
    "Tzuriel Guajardo",
    "Adrian Hernandez",
    "Emily Hernandez-Sandoval",
    "Hong Le",
    "Edwin Lopez Moreno",
    "Alondra Mendoza",
    "Brianna Newton",
    "Sandra Nguyen",
    "Nicole Nuevo",
    "Henry Perez-Ramirez",
    "Maria Rivera Contreras",
    "Michael Rojas Xenitis",
    "Xavier Sanchez",
    "Jessie Santana",
    "Antionne Showels",
    "Didier Thorpe",
    "Juan Vazquez Hernandez",
  ],
  "3rd": [
    "Dianelis Artelles Reyes",
    "Arnold Barrera Barrera",
    "Frank Castillo Rodriguez",
    "Karina Chavez",
    "Miguel Chehin",
    "Kaleb Cooksey",
    "Emanuel Cruz Frometa",
    "Paul Hung Delrio",
    "Katherine Funes Valladares",
    "Yeslyn Guevara Mendoza",
    "Anabel Guevara",
    "Maria Guillen Rivera",
    "Haider Hassan",
    "Jaden Liboy",
    "Rahimullah Mangal",
    "Catherine Montano Lores",
    "Elisbeth Montenegro Gonzalez",
    "Saul Olalde",
    "Jairo Polo Correa",
    "Humira Rasikh",
    "Barbaro Texido Pupo",
    "Kevin Villanueva",
  ],
  "5th": [
    "Andrew Camareno Aguilera",
    "Tung Do",
    "Oscar Garcia",
    "Zuriht Hernandez Cruz",
    "Jared Hernandez",
    "Yesenia Herrejon",
    "Wood Tayvia Hornsby",
    "Matiullah Khana Jan",
    "Jaiden Madyun",
    "Juan Martinez Rangel",
    "Eric Martinez",
    "Alagio Montalvo",
    "Doanh Nguyen",
    "Jorge Ortiz Duran",
    "Esteban Perez-Hernandez",
    "Toba Rahmani",
    "Rafael Rendon Catzin",
    "Alden Riquelmy",
    "Alondra Robles Elizalde",
    "Jamie Rocha Rios",
    "Joselyn Romero",
    "Diana Salazar-Almazan",
    "Kryztal Sanchez",
    "Jeremy Sorenson",
    "Tamana Timori",
  ],
  "6th": [
    "Luis Abrego Baltazar",
    "Razan Fouz Aldeen Al Zoubi",
    "Mariana Alarcon Esteban",
    "Lisandra Alonso Leal",
    "Nyrell Avila Gil",
    "Selvin Ayala Lanza",
    "Andrea Caceres Cabrera",
    "Steven Cantor",
    "Paul Don Delrio",
    "Deniel Dorvigny Mesa",
    "Maria Jimenez Rivera",
    "Diego Lopez Robles",
    "Omar Martinez",
    "Rachelys Matos Martinez",
    "Magdiel Ortiz Gonzalez",
    "Jostin Osorto Escobar",
    "Nicolle Ramirez Jaimes",
    "Osman Ramos Bolanos",
    "Marcos Rivas Ramos",
    "Marlon Rivas Ramos",
    "Keyla Rodriguez Peguero",
    "Yuniesky Ronda Ramirez",
    "Angela Sandoval Miranda",
    "Gerardo Sandoval",
    "Nelian Suarez Legra",
    "Stanley Trochez Rodriguez",
    "Sandy Turcios Flores",
    "Nidia Verde Gomez",
    "Ahnafullah Wahidi",
    "Mohammad Omar Yousufzai",
  ],
  "7th": [
    "Leonardo Acevedo Quinones",
    "Yilian Boza Mendoza",
    "Angel Charon Fuste",
    "Lisdany Fente Cepero",
    "Miguel Figueroa Fernandez",
    "Samantha Flores Castelan",
    "Meybelin Flores Guzman",
    "Francisco Garcia Hernandez",
    "Victoria Gastelum",
    "Maykel Gonzalez Carbo",
    "Erik Felipe Guerrero Hernandez",
    "Josefina Hernandez Perez",
    "Ha Van Hoang",
    "Yareli Jaramillo Luvianos",
    "Kenny Labrada Ramirez",
    "Lisandra Leon",
    "Angie Sofia Lopez Simeon",
    "Aylin Mondragon Dominguez",
    "Thi Anh Thu Nguyen",
    "Perla Olvera Vazquez",
    "Jarlin Palma Lopez",
    "Mohammad Rahmani",
    "Juan Reyes Prudencio",
    "Meydi Rodriguez Zelaya",
    "Edith Santos Soriano",
    "Malik Smith",
  ],
};

export default students;
