const students = {
  "1st": [
    "Cristian Amezcua",
    "Michelle Angel Mendez",
    "Oliver Brown",
    "Giorgia Cobas Pons",
    "Micah Corgill",
    "Juleous Don",
    "Javion Gallegos",
    "Alfredo Gonzalez",
    "Gavin Latas",
    "Javier Leyva Bello",
    "Mark Maldonado",
    "Frank Martinez",
    "Adrian Mejia Posadas",
    "Tony Mora Gonzalez",
    "Zaid Ordaz-Alvarado",
    "Lotfullah Pardis",
    "Erik Pelagio",
    "Johan Leonel Rodriguez Espinal",
    "Kevin Santana",
    "Brooklyn Scott Mitchell",
    "Wudassie Tafesse",
    "Adrian Tovar-Rodriguez",
    "Jaeden Woods",
    "Sebastian Vasquez Rico",
    "Aaron Velasco-Pina",
    "Cristina Villarreal",
    "Mohamad Zaloukh",
  ],
  "2nd": [
    "Alina Afalla",
    "Keren Banegas Murillo",
    "Jeremiah Beyene",
    "Estefany Botello-Ayala",
    "Zorah Brooks Richardson",
    "Cristhian Carrillo Manzanares",
    "Maria Chavez Martinez",
    "Mariah Cheairs",
    "A'mya Collins",
    "Zullal Fayazi",
    "Bryan Grimaldo Elias",
    "Tzuriel Guajardo",
    "Emily Hernandez-Sandoval",
    "Ky Anh Lam",
    "Hong Le",
    "Edwin Lopez Moreno",
    "Sandra Nguyen",
    "Nicole Nuevo",
    "Juan Perez-Almanza",
    "Henry Perez-Ramirez",
    "Maria Rivera Contreras",
    "Angel Sanchez",
    "Xavier Sanchez",
    "Jessie Santana",
    "Antionne Showels",
    "Didier Thorpe",
    "Juan Vazquez Hernandez",
    "Victor Zavala-Hernandez",
  ],
  "3rd": [
    "Dianelis Artelles Reyes",
    "Frank Castillo Rodriguez",
    "Miguel Chehin",
    "Kaleb Cooksey",
    "Emanuel Cruz Frometa",
    "Paul Hung Delrio",
    "Anabel Guevara",
    "Maria Guillen Rivera",
    "Haider Hassan",
    "Jaden Liboy",
    "Rahimullah Mangal",
    "Catherine Montano Lores",
    "Elisbeth Montenegro Gonzalez",
    "Jairo Polo Correa",
    "Ilsin Reynoso Lorenzana",
    "Barbaro Texido Pupo",
    "Kevin Villanueva",
    "Mark Vinogradov",
  ],
  "5th": [
    "Adrian Aguilar",
    "Jaquelinne Brito Palomino",
    "Carter Cool",
    "Tung Do",
    "Naila Gamon Fernandez",
    "Oscar Garcia",
    "Zuriht Hernandez Cruz",
    "Jared Hernandez",
    "Jaiden Madyun",
    "Eric Martinez",
    "Juan Martinez Rangel",
    "Rafael Rendon Catzin",
    "Alden Riquelmy",
    "Alondra Robles Elizalde",
    "Jamie Rocha Rios",
    "Nairea Roland",
    "Joselyn Romero",
    "Diana Salazar-Almazan",
    "Kryztal Sanchez",
    "Tamana Timori",
    "Fabiola Torres Arnaez",
    "Jocelin Perez",
  ],
  "6th": [
    "Luis Abrego Baltazar",
    "Razan Fouz Aldeen Al Zoubi",
    "Mariana Alarcon Esteban",
    "Lisandra Alonso Leal",
    "Selvin Ayala Lanza",
    "Andrea Caceres Cabrera",
    "Steven Cantor",
    "Paul Don Delrio",
    "Deniel Dorvigny Mesa",
    "Maria Jimenez Rivera",
    "Andrea Landeros Filomeno",
    "Omar Martinez",
    "Rachelys Matos Martinez",
    "Cinthia Mendoza Escalera",
    "David Montoya Osorio",
    "Magdiel Ortiz Gonzalez",
    "Jostin Osorto Escobar",
    "Nicolle Ramirez Jaimes",
    "Osman Ramos Bolanos",
    "Marcos Rivas Ramos",
    "Marlon Rivas Ramos",
    "Keyla Rodriguez Peguero",
    "Yuniesky Ronda Ramirez",
    "Angela Sandoval Miranda",
    "Gerardo Sandoval",
    "Nelian Suarez Legra",
    "Stanley Trochez Rodriguez",
    "Sandy Turcios Flores",
    "Nidia Verde Gomez",
    "Ahnafullah Wahidi",
    "Mohammad Omar Yousufzai",
  ],
  "7th": [
    "Leonardo Acevedo Quinones",
    "Yilian Boza Mendoza",
    "Angel Charon Fuste",
    "Karina Chavez",
    "Lisdany Fente Cepero",
    "Miguel Figueroa Fernandez",
    "Samantha Flores Castelan",
    "Meybelin Flores Guzman",
    "Francisco Garcia Hernandez",
    "Victoria Gastelum",
    "Maykel Gonzalez Carbo",
    "Josefina Hernandez Perez",
    "Yareli Jaramillo Luvianos",
    "Kenny Labrada Ramirez",
    "Lisandra Leon",
    "Diego Lopez Robles",
    "Angie Sofia Lopez Simeon",
    "Thi Anh Thu Nguyen",
    "Saul Olalde",
    "Perla Olvera Vazquez",
    "Jarlin Palma Lopez",
    "Mohammad Rahmani",
    "Juan Reyes Prudencio",
    "Valeria Rojas Luna",
    "Edith Santos Soriano",
    "Malik Smith",
  ],
};

export default students;
